// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAklg2mUQpg18dZI_pG6I_d50xXSbv0WRY',
    appId: '1:266993612037:web:582c4f4941ee169aa0336c',
    messagingSenderId: '266993612037',
    projectId: 'ashrbvfliar12308745',
    authDomain: 'ashrbvfliar12308745.firebaseapp.com',
    storageBucket: 'ashrbvfliar12308745.appspot.com',
    measurementId: 'G-MZSB9WG01H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKD4us6LR32mAmnp-gUJJLn9vYJAjx0zM',
    appId: '1:266993612037:android:34aa38d9fd7be594a0336c',
    messagingSenderId: '266993612037',
    projectId: 'ashrbvfliar12308745',
    storageBucket: 'ashrbvfliar12308745.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOEVXN1yciQgmTBa3Xfq1rfbFyKbBeX6c',
    appId: '1:266993612037:ios:0c331ada1f024965a0336c',
    messagingSenderId: '266993612037',
    projectId: 'ashrbvfliar12308745',
    storageBucket: 'ashrbvfliar12308745.appspot.com',
    iosBundleId: 'com.learning.myfirstapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOEVXN1yciQgmTBa3Xfq1rfbFyKbBeX6c',
    appId: '1:266993612037:ios:cc5074afc9595976a0336c',
    messagingSenderId: '266993612037',
    projectId: 'ashrbvfliar12308745',
    storageBucket: 'ashrbvfliar12308745.appspot.com',
    iosBundleId: 'com.learning.myfirstapp.RunnerTests',
  );
}
